name: zip-utils-ui ci/cd
on: workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: zip-utils-ui

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js latest version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
