name: Deploy to GitHub Pages

on:
  pull_request:
    types: [closed]
    branches: [dev, prod]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check.outputs.should-deploy }}
      source-branch: ${{ steps.check.outputs.source-branch }}
    steps:
      - name: Check deployment conditions
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" && ("${{ github.event.pull_request.base.ref }}" == "dev" || "${{ github.event.pull_request.base.ref }}" == "prod") ]]; then
            echo "should-deploy=true" >> $GITHUB_OUTPUT
            echo "source-branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && ("${{ github.ref_name }}" == "dev" || "${{ github.ref_name }}" == "prod") ]]; then
            echo "should-deploy=true" >> $GITHUB_OUTPUT
            echo "source-branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "should-deploy=false" >> $GITHUB_OUTPUT
            echo "source-branch=" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.should-deploy == 'true' }}
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.source-branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build:${{ needs.setup.outputs.source-branch }}
          echo "repo_suffix=${{ needs.setup.outputs.source-branch }}" >> $GITHUB_ENV
          cd dist/zip-utils-ui/browser

          mv index.csr.html index.html
          cp index.html 404.html
          cp ../../../robots.txt . || echo "robots.txt not found, skipping"
          cp ../../../sitemap.xml . || echo "sitemap.xml not found, skipping"

          # Create CNAME file dynamically based on environment
          if [ ${{ needs.setup.outputs.source-branch }} == "prod" ]; then
            echo "ziputils.com" > CNAME
          else
            echo "dev.ziputils.com" > CNAME
          fi

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: mochinikunj/zip-utils-ui-${{ env.repo_suffix }}
          path: compiled-js

      - name: Copy build files to target
        run: |
          cp -r dist/zip-utils-ui/browser/* compiled-js/

      - name: Copy Compiled JS
        run: |
          # Copy files from dist/zip-utils-ui/browser to compiled-js/, replacing existing files
          cp -r dist/zip-utils-ui/browser/* compiled-js/
          echo "Copied compiled JS files to compiled-js, replacing existing files"

      - name: Commit and Push from compiled-js to GitHub repo
        run: |
          cd compiled-js
          git config user.name "Nikunj Mochi"
          git config user.email "mochinikunj2@gmail.com "
          git add .
          git commit -m "Update compiled JS from zip-utils-ui's branch build"
          git push
